apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.branch }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.branch }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.branch }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.branch }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.branch }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1  
          securityContext:
            allowPrivilegeEscalation: true
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsUser: 82 
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config-{{ .Values.branch }}
            - secretRef:
                name: {{ .Chart.Name }}-secret-{{ .Values.branch }}            
          ports:
          - containerPort: {{ .Values.containerPort }}
          
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}   
      